on:
  repository_dispatch:
    types: [run-playwright]

jobs:
  test:
    if: github.ref == 'refs/heads/feat/ImplementacionSlack'
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar evento y rama
        run: |
          echo "Evento: ${{ github.event_name }}"
          echo "Rama: ${{ github.ref }}"
