name: Prueba Simple

on:
  workflow_dispatch: 
  push:
    branches:
      - feat/ImplementacionSlack

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "✅ Workflow ejecutado en la rama ${{ github.ref_name }}"
